// Translate the dumped SQLite (Turso) schema → Postgres DDL.
//   node src/scripts/sqliteSchemaToPg.mjs /tmp/turso-schema.sql /tmp/pg-schema.sql /tmp/pg-foreign-keys.sql
//
// Tables + indexes go to the schema file; foreign keys go to a companion file
// applied AFTER data load (so existing/orphan rows don't block the load).
import fs from 'node:fs';

const [, , inPath = '/tmp/turso-schema.sql', outPath = '/tmp/pg-schema.sql', fkPath = '/tmp/pg-foreign-keys.sql'] = process.argv;
const raw = fs.readFileSync(inPath, 'utf8');
const chunks = raw.split(/\n(?=-- (?:table|index|trigger): )/);

const tables = [], indexes = [], fks = [], notes = [];

// SQLite default expr → Postgres text-producing expr (format preserved per flavor)
const TS_ISO = `to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS"Z"')`;
const TS_SPACE = `to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS')`;
const UUID = `lower(replace(gen_random_uuid()::text,'-',''))`;

function rewriteDefaults(s) {
  s = s.replace(/lower\(hex\(randomblob\(\d+\)\)\)/gi, UUID);
  // timestamp functions — must run BEFORE the DATETIME type swap below
  s = s.replace(/strftime\(\s*'%Y-%m-%dT%H:%M:%SZ'\s*,\s*'now'\s*\)/gi, TS_ISO);
  s = s.replace(/datetime\(\s*'now'\s*\)/gi, TS_SPACE);
  s = s.replace(/\bCURRENT_TIMESTAMP\b/gi, TS_SPACE);
  return s;
}

function mapTypes(s) {
  s = s.replace(/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, 'bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  s = s.replace(/\bDATETIME\b/gi, 'text');          // SQLite affinity = text; app stores ISO strings
  s = s.replace(/\bINTEGER\b/gi, 'bigint');         // SQLite INTEGER is 64-bit (+ avoids unix-ms overflow)
  s = s.replace(/\bREAL\b/gi, 'double precision');  // SQLite REAL is 8-byte; keep precision for money
  return s;
}

function extractFks(table, body) {
  let i = 0;
  // table-level: [,] FOREIGN KEY (cols) REFERENCES tbl(cols) [ON DELETE x]
  body = body.replace(/,?\s*FOREIGN KEY\s*\(\s*([^)]+?)\s*\)\s*REFERENCES\s+"?(\w+)"?\s*\(\s*([^)]+?)\s*\)(\s+ON DELETE \w+)?/gi,
    (_, col, tbl, ref, onDel) => {
      fks.push(`ALTER TABLE ${table} ADD CONSTRAINT fk_${table}_${++i} FOREIGN KEY (${col}) REFERENCES ${tbl}(${ref})${onDel || ''};`);
      return '';
    });
  // column-level inline: <col> <type> ... REFERENCES tbl(col) [ON DELETE x]
  body = body.split('\n').map((line) => {
    const m = line.match(/^\s*"?(\w+)"?\s+.*?REFERENCES\s+"?(\w+)"?\s*\(\s*(\w+)\s*\)(\s+ON DELETE \w+)?/i);
    if (m && !/^\s*FOREIGN KEY/i.test(line)) {
      const [, src, tbl, ref, onDel] = m;
      fks.push(`ALTER TABLE ${table} ADD CONSTRAINT fk_${table}_${++i} FOREIGN KEY (${src}) REFERENCES ${tbl}(${ref})${onDel || ''};`);
      line = line.replace(/\s*REFERENCES\s+"?\w+"?\s*\(\s*\w+\s*\)(\s+ON DELETE \w+)?/i, '');
    }
    return line;
  }).join('\n');
  return body;
}

for (const chunk of chunks) {
  const header = chunk.match(/^-- (table|index|trigger): (\S+)/);
  if (!header) continue;
  const [, type, name] = header;
  let body = chunk.replace(/^-- (?:table|index|trigger): \S+\n/, '').trim();

  if (type === 'trigger') {
    notes.push(`-- DROPPED SQLite trigger ${name} — reimplement as a PG trigger function or enforce in app.`);
    continue;
  }
  if (type === 'index') {
    body = body.replace(/CREATE (UNIQUE )?INDEX\s+/i, (_m, u) => `CREATE ${u || ''}INDEX IF NOT EXISTS `);
    body = body.replace(/COALESCE\([^)]*\)/gi, (m) => `(${m})`); // expression index cols need parens in PG
    indexes.push(body.endsWith(';') ? body : body + ';');
    continue;
  }
  // table
  const tname = (body.match(/CREATE TABLE\s+"?(\w+)"?/i) || [, name])[1];
  body = rewriteDefaults(body);
  body = mapTypes(body);
  body = extractFks(tname, body);
  body = body.replace(/^CREATE TABLE\s+/i, 'CREATE TABLE IF NOT EXISTS ');
  body = body.replace(/,(\s*)\)/g, '$1)'); // tidy any trailing comma left by FK removal
  tables.push(body.endsWith(';') ? body : body + ';');
}

const schema = [
  '-- Postgres schema translated from the Turso/SQLite dump.',
  '-- Tables + indexes only; foreign keys are in the companion file (applied after data load).',
  '', ...tables.map((t) => t + '\n'),
  '-- ── Indexes ───────────────────────────────────────────', ...indexes,
  '', ...notes,
].join('\n');

fs.writeFileSync(outPath, schema + '\n');
fs.writeFileSync(fkPath, ['-- Foreign keys — apply AFTER data load.', ...fks].join('\n') + '\n');
console.error(`[translate] ${tables.length} tables, ${indexes.length} indexes, ${fks.length} FKs, ${notes.length} triggers dropped`);
